# Test and Deploy Simulator to GitHub Pages
name: Test and Deploy Simulator to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        working-directory: ./software/simulator
        run: npm ci
      - name: Build Vite app
        working-directory: ./software/simulator
        run: npm run build
      - name: Install Playwright Browsers
        working-directory: ./software/simulator
        run: npx playwright install --with-deps
      - name: Start Vite preview server
        working-directory: ./software/simulator
        run: |
          nohup npm run preview -- --host 0.0.0.0 &
      - name: Wait for app to be ready
        working-directory: ./software/simulator
        run: |
          npx wait-on http://localhost:4173 --timeout 30000
      - name: Run Playwright tests
        working-directory: ./software/simulator
        run: npx playwright test
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: software/simulator/test-results/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./software/simulator
        run: npm ci
      - name: Build Vite app
        working-directory: ./software/simulator
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./software/simulator/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
